import { useState } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, ExternalLink, FileText, Filter, Globe2, Search, ShieldCheck, X } from "lucide-react";
import "./evidence.css";

type EvidenceSource = { id: string; title: string; publisher: string; type: "Company" | "Industry" | "Government" | "News"; date: string; confidence: number; verified: boolean; snippet: string; url: string };
type Relationship = { id: string; source: string; target: string; relationship: string; confidence: number; verified: boolean; sourceCount: number };
const relationships: Relationship[] = [
 { id: "r1", source: "Supplier A", target: "Your Company", relationship: "SUPPLIES", confidence: 96, verified: true, sourceCount: 4 },
 { id: "r2", source: "Supplier A", target: "Factory X", relationship: "MANUFACTURES", confidence: 94, verified: true, sourceCount: 3 },
 { id: "r3", source: "Supplier B", target: "Lithium", relationship: "USES_MATERIAL", confidence: 88, verified: true, sourceCount: 3 },
 { id: "r4", source: "Factory X", target: "Region A", relationship: "LOCATED_IN", confidence: 99, verified: true, sourceCount: 5 },
 { id: "r5", source: "Lithium", target: "Processing Facility D", relationship: "PROCESSES", confidence: 83, verified: true, sourceCount: 2 },
];
const evidenceSources: Record<string, EvidenceSource[]> = {
 r1: [{ id: "s1", title: "Supplier Relationship Disclosure", publisher: "Company Annual Report", type: "Company", date: "12 Aug 2026", confidence: 97, verified: true, snippet: "The company identifies Supplier A as an active supplier within its battery component procurement network.", url: "#" }, { id: "s2", title: "Battery Supply Chain Overview", publisher: "Industry Research Group", type: "Industry", date: "03 Jul 2026", confidence: 94, verified: true, snippet: "Supplier A is referenced as a component supplier serving organizations operating in the battery sector.", url: "#" }, { id: "s3", title: "Corporate Supplier Information", publisher: "Supplier A", type: "Company", date: "28 Jun 2026", confidence: 95, verified: true, snippet: "Public company information describes Supplier A's business relationships and component supply activities.", url: "#" }],
 r2: [{ id: "s4", title: "Manufacturing Operations Report", publisher: "Supplier A", type: "Company", date: "08 Aug 2026", confidence: 95, verified: true, snippet: "Factory X is listed among manufacturing facilities associated with Supplier A's production operations.", url: "#" }, { id: "s5", title: "Industrial Facility Database", publisher: "Industry Research Group", type: "Industry", date: "21 Jul 2026", confidence: 92, verified: true, snippet: "Factory X is identified as a manufacturing facility connected to Supplier A.", url: "#" }],
 r3: [{ id: "s6", title: "Battery Material Analysis", publisher: "Materials Intelligence Report", type: "Industry", date: "02 Aug 2026", confidence: 90, verified: true, snippet: "Lithium is identified as a critical material input for the battery products associated with Supplier B.", url: "#" }, { id: "s7", title: "Material Composition Documentation", publisher: "Supplier B", type: "Company", date: "19 Jul 2026", confidence: 87, verified: true, snippet: "Supplier B's product documentation references lithium-based battery material requirements.", url: "#" }],
 r4: [{ id: "s8", title: "Facility Location Record", publisher: "Corporate Facility Information", type: "Company", date: "10 Aug 2026", confidence: 99, verified: true, snippet: "Factory X is registered at a facility address located within Region A.", url: "#" }],
 r5: [{ id: "s9", title: "Lithium Processing Network", publisher: "Industry Research Group", type: "Industry", date: "29 Jul 2026", confidence: 84, verified: true, snippet: "Processing Facility D is identified as part of the lithium refinement network.", url: "#" }, { id: "s10", title: "Processing Facility Information", publisher: "Facility Operator", type: "Company", date: "14 Jul 2026", confidence: 82, verified: true, snippet: "Facility D describes lithium processing activities as part of its industrial operations.", url: "#" }],
};

function Evidence() {
 const [selected, setSelected] = useState(relationships[0]); const [search, setSearch] = useState(""); const [verifiedOnly, setVerifiedOnly] = useState(false); const sources = evidenceSources[selected.id] || [];
 const filteredRelationships = relationships.filter((item) => { const query = search.toLowerCase(); return (!query || [item.source, item.target, item.relationship].some((value) => value.toLowerCase().includes(query))) && (!verifiedOnly || item.verified); });
 return <div className="evidence-page"><div className="evidence-header"><div><div className="evidence-eyebrow"><ShieldCheck size={14} />SOURCE-BACKED INTELLIGENCE</div><h1>Evidence Intelligence</h1><p>Trace every discovered relationship back to the evidence that supports it.</p></div><div className="evidence-header-actions"><div className="evidence-search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search relationships..." /></div><button className={`evidence-filter ${verifiedOnly ? "active" : ""}`} onClick={() => setVerifiedOnly(!verifiedOnly)}><Filter size={16} />Verified</button></div></div>
 <div className="evidence-layout"><section className="relationship-panel glass-panel"><div className="panel-heading"><div><span className="panel-kicker">DISCOVERED</span><h2>Relationships</h2></div><span className="count-pill">{filteredRelationships.length}</span></div><div className="relationship-cards">{filteredRelationships.map((relationship) => <button key={relationship.id} className={`relationship-card ${selected.id === relationship.id ? "selected" : ""}`} onClick={() => setSelected(relationship)}><div className="relationship-card-top"><div className="relationship-node"><span>{relationship.source}</span><ChevronRight size={14} /><span>{relationship.target}</span></div><ChevronRight size={16} className="relationship-arrow" /></div><div className="relationship-card-bottom"><span className="relationship-type">{relationship.relationship}</span><span className="relationship-confidence">{relationship.confidence}%</span><span className="source-count"><FileText size={12} />{relationship.sourceCount} sources</span></div></button>)}</div></section>
 <section className="evidence-detail glass-panel"><div className="detail-header"><div><span className="panel-kicker">RELATIONSHIP EVIDENCE</span><h2>{selected.relationship}</h2><div className="detail-path"><span>{selected.source}</span><ChevronRight size={15} /><span>{selected.target}</span></div></div><button className="detail-close" onClick={() => setSelected(relationships[0])}><X size={16} /></button></div><div className="confidence-summary"><div className="confidence-main"><div className="confidence-circle"><strong>{selected.confidence}</strong><span>%</span></div><div><span>Relationship confidence</span><strong>{selected.verified ? "Verified with supporting evidence" : "Requires verification"}</strong></div></div><div className="verified-status"><CheckCircle2 size={17} />Verified</div></div><div className="evidence-divider" /><div className="source-heading"><div><span className="panel-kicker">PROVENANCE</span><h3>Supporting Sources</h3></div><span>{sources.length} sources</span></div><div className="source-list">{sources.map((source) => <SourceCard key={source.id} source={source} />)}</div><div className="evidence-note"><ShieldCheck size={18} /><div><strong>Evidence-backed relationship</strong><p>This relationship is displayed because the investigation engine found supporting evidence from permitted sources. Confidence represents the verification result, not a claim of absolute certainty.</p></div></div></section></div></div>;
}
function SourceCard({ source }: { source: EvidenceSource }) { const Icon = source.type === "Government" ? ShieldCheck : source.type === "News" ? Globe2 : FileText; return <article className="source-card"><div className="source-icon"><Icon size={19} /></div><div className="source-content"><div className="source-top"><div><span className="source-type">{source.type}</span><h4>{source.title}</h4></div>{source.verified && <span className="source-verified"><CheckCircle2 size={13} />Verified</span>}</div><div className="source-meta"><span>{source.publisher}</span><span><CalendarDays size={12} />{source.date}</span><span>Confidence {source.confidence}%</span></div><p className="source-snippet">“{source.snippet}”</p><div className="source-actions"><button>View source<ExternalLink size={13} /></button><button><Globe2 size={13} />Open evidence</button></div></div></article>; }
export default Evidence;
